version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - DewaldOosthuizen
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns:
          - "*"
    assignees:
      - DewaldOosthuizen
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    target-branch: main
    groups:
      dev-dependencies:
        patterns:
          - "*"
    assignees:
      - DewaldOosthuizen
